apiVersion: v1
kind: Service
metadata:
  name: helloworldservice
spec:
  selector:
    app: hello-world
  ports:
    - name: web
      protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 30001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 5
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: tutum/hello-world
        ports:
        - containerPort: 80
